package com.skycong.file.dao.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_api_interface
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class InterfaceModel implements Serializable {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_api_interface.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   接口名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_api_interface.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   接口描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_api_interface.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   请求URI
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_api_interface.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   请求方法
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_api_interface.method
     *
     * @mbg.generated
     */
    private String method;

    /**
     * Database Column Remarks:
     *   请求content_type
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_api_interface.request_content_type
     *
     * @mbg.generated
     */
    private String requestContentType;

    /**
     * Database Column Remarks:
     *   请求参数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_api_interface.request_params
     *
     * @mbg.generated
     */
    private String requestParams;

    /**
     * Database Column Remarks:
     *   请求备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_api_interface.request_remark
     *
     * @mbg.generated
     */
    private String requestRemark;

    /**
     * Database Column Remarks:
     *   响应content_type
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_api_interface.response_content_type
     *
     * @mbg.generated
     */
    private String responseContentType;

    /**
     * Database Column Remarks:
     *   响应内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_api_interface.response_content
     *
     * @mbg.generated
     */
    private String responseContent;

    /**
     * Database Column Remarks:
     *   响应备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_api_interface.response_remark
     *
     * @mbg.generated
     */
    private String responseRemark;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_api_interface.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   最后修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_api_interface.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_api_interface.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_api_interface.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_api_interface
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_api_interface.id
     *
     * @return the value of tb_api_interface.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_api_interface.id
     *
     * @param id the value for tb_api_interface.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_api_interface.name
     *
     * @return the value of tb_api_interface.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_api_interface.name
     *
     * @param name the value for tb_api_interface.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_api_interface.description
     *
     * @return the value of tb_api_interface.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_api_interface.description
     *
     * @param description the value for tb_api_interface.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_api_interface.address
     *
     * @return the value of tb_api_interface.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_api_interface.address
     *
     * @param address the value for tb_api_interface.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_api_interface.method
     *
     * @return the value of tb_api_interface.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_api_interface.method
     *
     * @param method the value for tb_api_interface.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_api_interface.request_content_type
     *
     * @return the value of tb_api_interface.request_content_type
     *
     * @mbg.generated
     */
    public String getRequestContentType() {
        return requestContentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_api_interface.request_content_type
     *
     * @param requestContentType the value for tb_api_interface.request_content_type
     *
     * @mbg.generated
     */
    public void setRequestContentType(String requestContentType) {
        this.requestContentType = requestContentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_api_interface.request_params
     *
     * @return the value of tb_api_interface.request_params
     *
     * @mbg.generated
     */
    public String getRequestParams() {
        return requestParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_api_interface.request_params
     *
     * @param requestParams the value for tb_api_interface.request_params
     *
     * @mbg.generated
     */
    public void setRequestParams(String requestParams) {
        this.requestParams = requestParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_api_interface.request_remark
     *
     * @return the value of tb_api_interface.request_remark
     *
     * @mbg.generated
     */
    public String getRequestRemark() {
        return requestRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_api_interface.request_remark
     *
     * @param requestRemark the value for tb_api_interface.request_remark
     *
     * @mbg.generated
     */
    public void setRequestRemark(String requestRemark) {
        this.requestRemark = requestRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_api_interface.response_content_type
     *
     * @return the value of tb_api_interface.response_content_type
     *
     * @mbg.generated
     */
    public String getResponseContentType() {
        return responseContentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_api_interface.response_content_type
     *
     * @param responseContentType the value for tb_api_interface.response_content_type
     *
     * @mbg.generated
     */
    public void setResponseContentType(String responseContentType) {
        this.responseContentType = responseContentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_api_interface.response_content
     *
     * @return the value of tb_api_interface.response_content
     *
     * @mbg.generated
     */
    public String getResponseContent() {
        return responseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_api_interface.response_content
     *
     * @param responseContent the value for tb_api_interface.response_content
     *
     * @mbg.generated
     */
    public void setResponseContent(String responseContent) {
        this.responseContent = responseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_api_interface.response_remark
     *
     * @return the value of tb_api_interface.response_remark
     *
     * @mbg.generated
     */
    public String getResponseRemark() {
        return responseRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_api_interface.response_remark
     *
     * @param responseRemark the value for tb_api_interface.response_remark
     *
     * @mbg.generated
     */
    public void setResponseRemark(String responseRemark) {
        this.responseRemark = responseRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_api_interface.create_by
     *
     * @return the value of tb_api_interface.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_api_interface.create_by
     *
     * @param createBy the value for tb_api_interface.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_api_interface.update_by
     *
     * @return the value of tb_api_interface.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_api_interface.update_by
     *
     * @param updateBy the value for tb_api_interface.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_api_interface.create_time
     *
     * @return the value of tb_api_interface.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_api_interface.create_time
     *
     * @param createTime the value for tb_api_interface.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_api_interface.update_time
     *
     * @return the value of tb_api_interface.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_api_interface.update_time
     *
     * @param updateTime the value for tb_api_interface.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}