package com.skycong.file.dao.mapper;


import com.skycong.file.dao.model.InterfaceModel;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface InterfaceModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_api_interface
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_api_interface
     *
     * @mbg.generated
     */
    int insertSelective(InterfaceModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_api_interface
     *
     * @mbg.generated
     */
    InterfaceModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_api_interface
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InterfaceModel record);

    List<InterfaceModel> findAll();

    List<InterfaceModel> findByKeyword(String keyword);
}